"""Add active box to pick_list

Revision ID: 2ba3cb596e55
Revises: a1b2c3d4e5f6
Create Date: 2026-08-18 13:00:29.916840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ba3cb596e55'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pick_assignments', 'status')
    op.add_column('pick_lists', sa.Column('active_box_carton_id', sa.Integer(), nullable=True))
    op.add_column('pick_lists', sa.Column('active_box_contents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'pick_lists', 'carton_types', ['active_box_carton_id'], ['id'])
    op.drop_index('ix_sales_items_barcode', table_name='sales_items')
    op.create_index(op.f('ix_sales_items_primary_barcode'), 'sales_items', ['primary_barcode'], unique=True)
    op.create_index(op.f('ix_sales_items_secondary_barcode'), 'sales_items', ['secondary_barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_items_secondary_barcode'), table_name='sales_items')
    op.drop_index(op.f('ix_sales_items_primary_barcode'), table_name='sales_items')
    op.create_index('ix_sales_items_barcode', 'sales_items', ['primary_barcode'], unique=True)
    op.drop_constraint(None, 'pick_lists', type_='foreignkey')
    op.drop_column('pick_lists', 'active_box_contents')
    op.drop_column('pick_lists', 'active_box_carton_id')
    op.add_column('pick_assignments', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'assigned'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
