"""Add is_audited to PickListBox

Revision ID: 625ba9e9ff0f
Revises: 2ba3cb596e55
Create Date: 2026-08-18 15:36:25.253281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625ba9e9ff0f'
down_revision = '2ba3cb596e55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('pick_list_boxes', sa.Column('is_audited', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'pick_lists', 'sales_orders', ['sales_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pick_lists', type_='foreignkey')
    op.drop_column('pick_list_boxes', 'is_audited')
    # ### end Alembic commands ###
