"""Add dual barcodes

Revision ID: 73b56e2529f9
Revises: d1a2b3c4d5e6
Create Date: 2026-08-13 12:08:34.809554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b56e2529f9'
down_revision = 'd1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pick_assignments', 'status')
    op.add_column('sales_items', sa.Column('primary_barcode', sa.String(), nullable=False))
    op.add_column('sales_items', sa.Column('secondary_barcode', sa.String(), nullable=True))
    op.drop_index('ix_sales_items_barcode', table_name='sales_items')
    op.create_index(op.f('ix_sales_items_primary_barcode'), 'sales_items', ['primary_barcode'], unique=True)
    op.create_index(op.f('ix_sales_items_secondary_barcode'), 'sales_items', ['secondary_barcode'], unique=False)
    op.drop_column('sales_items', 'barcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_items', sa.Column('barcode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sales_items_secondary_barcode'), table_name='sales_items')
    op.drop_index(op.f('ix_sales_items_primary_barcode'), table_name='sales_items')
    op.create_index('ix_sales_items_barcode', 'sales_items', ['barcode'], unique=True)
    op.drop_column('sales_items', 'secondary_barcode')
    op.drop_column('sales_items', 'primary_barcode')
    op.add_column('pick_assignments', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'assigned'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
