"""Add LPO model and sales_person_id to picklist

Revision ID: 8c22c05b9573
Revises: 
Create Date: 2026-08-11 16:05:24.442697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c22c05b9573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lpos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lpo_number', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('sales_person_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('signed_lpo_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sales_person_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lpos_id'), 'lpos', ['id'], unique=False)
    op.create_index(op.f('ix_lpos_lpo_number'), 'lpos', ['lpo_number'], unique=True)
    op.create_foreign_key(None, 'pick_list_items', 'pick_list_boxes', ['box_id'], ['id'])
    op.add_column('pick_lists', sa.Column('sales_person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pick_lists', 'users', ['sales_person_id'], ['id'])
    op.alter_column('raw_materials', 'weight_unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'kg'::character varying"))
    op.drop_column('raw_materials', 'market_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_materials', sa.Column('market_type', sa.VARCHAR(), server_default=sa.text("'both'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('raw_materials', 'weight_unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'kg'::character varying"))
    op.drop_constraint(None, 'pick_lists', type_='foreignkey')
    op.drop_column('pick_lists', 'sales_person_id')
    op.drop_constraint(None, 'pick_list_items', type_='foreignkey')
    op.drop_index(op.f('ix_lpos_lpo_number'), table_name='lpos')
    op.drop_index(op.f('ix_lpos_id'), table_name='lpos')
    op.drop_table('lpos')
    # ### end Alembic commands ###
