"""remove emp_id and phone from sales_users

Revision ID: aba7b7e6fe13
Revises: d1ab10596d30
Create Date: 2026-08-31 11:03:40.643839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba7b7e6fe13'
down_revision = 'd1ab10596d30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_users_emp_id', table_name='sales_users')
    op.drop_column('sales_users', 'phone')
    op.drop_column('sales_users', 'emp_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_users', sa.Column('emp_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sales_users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_sales_users_emp_id', 'sales_users', ['emp_id'], unique=False)
    # ### end Alembic commands ###
