"""add delivery_date

Revision ID: c77f2ba90eec
Revises: 8c22c05b9573
Create Date: 2026-08-11 16:32:18.524611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77f2ba90eec'
down_revision = '8c22c05b9573'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lpos', sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pick_lists', sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pick_lists', 'delivery_date')
    op.drop_column('lpos', 'delivery_date')
    # ### end Alembic commands ###
