"""Add source to lpos

Revision ID: fe378d9d77f4
Revises: c77f2ba90eec
Create Date: 2026-08-11 18:39:43.516084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe378d9d77f4'
down_revision = 'c77f2ba90eec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lpos', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('lpos', 'sales_person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lpos', 'sales_person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lpos', 'source')
    # ### end Alembic commands ###
